{
 "title": "dash-forum-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API BASIC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "API uptime",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "USER LOGGED",
     "type": "stat",
     "description": "Quantidade de usuários logados nos últimos minutos",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total[1m])",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "JDBC POOL",
     "type": "stat",
     "description": "Pool de conexões JDBC",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CONNECTION STATE",
     "type": "timeseries",
     "description": "Estado das conexões com o database",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "\nhikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "stat",
     "description": "Hora da inicialização da API",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AUTH ERRORS",
     "type": "stat",
     "description": "Erros de autenticação no último minuto",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB CONNECTION TIMEOUT",
     "type": "stat",
     "description": "Conexões com o database em timeout",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WARN & ERROR LOG",
     "type": "timeseries",
     "description": "Warnings e Erros logados nos últimos 5 minutos",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[5m]))",
       "legendFormat": "warn"
      },
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "TOTAL REQUESTS",
   "type": "stat",
   "description": "Número de requisições no último minuto",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Número de erros 500 no último minuto",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Taxa de erros nos últimos 5 minutos",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Tempo de resposta no último minuto",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "Latência média por minuto",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  }
 ]
}